language: python
group: travis_latest
dist: xenial
os: linux
sudo: false

git:
    submodules: false

env:
    global:
        - TOX_ARG=''

stages:
    - name: Generic tests

    - name: Cron tests
      if: (type = cron) OR (branch = master)


matrix:
    # Don't wait for allowed failures
    fast_finish: true
    include:
        - name: "3.7"
          env: TOX_ENV='py37'
          python: "3.7"
          stage: Generic tests

        - name: "3.6"
          env: TOX_ENV='py36'
          python: "3.6"
          stage: Cron tests

        - name: "3.6-numpydev"
          env: TOX_ENV='py36-numpydev'
          python: "3.6"
          stage: Cron tests

        - name: "3.7-numpydev"
          env: TOX_ENV='py37-numpydev'
          python: "3.7"
          stage: Cron tests

        - name: "3.6-astropydev"
          env: TOX_ENV='py36-astropydev'
          python: "3.6"
          stage: Cron tests

        - name: "3.7-astropydev"
          env: TOX_ENV='py37-astropydev'
          python: "3.7"
          stage: Cron tests

        - name: "3.8"
          env: TOX_ENV='py38'
          python: "3.6"
          stage: Generic tests

        - name: "3.8-astropydev"
          env: TOX_ENV='py38-astropydev'
          python: "3.6"
          stage: Generic tests

        - name: "3.8-numpydev"
          env: TOX_ENV='py38-numpydev'
          python: "3.6"
          stage: Generic tests
          # TODO change generic tests to cron jobs

before_install:
        - git clone git://github.com/astropy/ci-helpers.git --depth 1
          # We do not want to create the test env
        - echo "" > ci-helpers/travis/setup_dependencies_common.sh
        - source ci-helpers/travis/setup_conda.sh
        - pip install tox

script:
  - tox -e $TOX_ENV $TOX_ARG

# Hook travis into matrix channel for notifications
notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MFNvbGFyRHJldyUzQW1hdHJpeC5vcmcvJTIxaGtXQ2l5aFF5eGlZSmxVdEtGJTNBbWF0cml4Lm9yZw"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never
