# Language options
language: python
python:
        - "3.6"

git:
    submodules: false

env:
    global:
        - PYTHON_VERSION=3.6
        - SETUP_CMD='test'
        - MAIN_CMD='python setup.py'
        - CONDA_DEPENDENCIES='Cython astropy scipy h5py matplotlib mpmath pytest'
        - CONDA_ALL_DEPENDENCIES='Cython astropy scipy h5py matplotlib mpmath pytest'
        - PIP_DEPENDENCIES='roman lmfit colorama codecov mypy'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        - env: PYTHON_VERSION=3.6 SETUP_CMD='test --coverage'

        - env: PYTHON_VERSION=3.7 SETUP_CMD='test'

install:
        - git clone git://github.com/astropy/ci-helpers.git --depth 1
        - source ci-helpers/travis/setup_conda.sh
    
# Run the tests
script:
    - $MAIN_CMD $SETUP_CMD
    - mypy plasmapy
    
# Assess test coverage
after_success:
        - codecov

# Hook travis into matrix channel for notifications
notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MFNvbGFyRHJldyUzQW1hdHJpeC5vcmcvJTIxaGtXQ2l5aFF5eGlZSmxVdEtGJTNBbWF0cml4Lm9yZw"
        on_success: change  # always|never|change
        on_failure: always
on_start: never
