# Language options
language: python
python:
        - "3.6"

git:
    submodules: false

env:
    global:
        - PYTHON_VERSION=3.6
        - SETUP_CMD='test'
        - NUMPY_VERSION='stable'
        - ASTROPY_VERSION='stable'
        - MAIN_CMD='python setup.py'
        - CONDA_DEPENDENCIES='Cython scipy h5py matplotlib mpmath pytest'
        - CONDA_ALL_DEPENDENCIES='Cython scipy h5py matplotlib mpmath pytest'
        - PIP_DEPENDENCIES='roman lmfit colorama codecov'

stages:
    - name: Generic tests

    - name: Cron tests
      if: type = cron

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        - env: PYTHON_VERSION=3.6 
          stage: Generic tests

        - env: PYTHON_VERSION=3.7 SETUP_CMD='test --coverage'
          stage: Generic tests
          
        - env: PYTHON_VERSION=3.8 CONDA_ALL_DEPENDENCIES='Cython scipy h5py matplotlib mpmath pytest -c conda-forge/label/pre-3.8 python'
          stage: Generic tests

        - env: ASTROPY_VERSION='dev'
          stage: Cron tests

        - env: NUMPY_VERSION='dev'
          stage: Cron tests

        - env: NUMPY_VERSION='dev' ASTROPY_VERSION='dev'
          stage: Cron tests

install:
        - git clone git://github.com/astropy/ci-helpers.git --depth 1
        - source ci-helpers/travis/setup_conda.sh

# Run the tests
script:
    - $MAIN_CMD $SETUP_CMD

# Assess test coverage
after_success:
        - codecov

# Hook travis into matrix channel for notifications
notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MFNvbGFyRHJldyUzQW1hdHJpeC5vcmcvJTIxaGtXQ2l5aFF5eGlZSmxVdEtGJTNBbWF0cml4Lm9yZw"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never
