[default]

[default.extend-words]
aas = "aas"
arange = "arange"
ba = "ba"
dne = "dne"
explin = "explin"
hax = "hax"
iy = "iy"
nd = "nd"
rety = "rety"
newshape = "newshape"
texttt = "texttt"
nbins = "nbins"
