name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
variables:
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/plasmapy/plasmapy/_build/results?buildId=$(Build.BuildId)"
  CIBW_BUILD: cp36-* cp37-* cp38-*
  CIBW_SKIP: "*-win32 *-manylinux1_i686"

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: PlasmaPy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'
    exclude:
    - '*dev*'
    - '*pre*'
    - '*post*'

jobs:
- template: run-tox-env.yml@OpenAstronomy
  parameters:
    submodules: false
    coverage: codecov
    posargs: -n=4
    envs:
      - macos: py37
        name: py37_macos

      - windows: py36
        name: py36_windows

      - linux: py37
        name: py37_linux

      - linux: py38
        name: py38_linux

      - linux: py36-conda
        name: py36_conda
        libraries: {}

      - linux: py36-astropy31
        name: py36_astropy31

      - linux: py37-astropydev
        name: py37_astropydev

      - linux: py37-numpydev
        name: py37_numpydev

      - linux: py36-minimal-conda
        name: py36_minimal_conda

# On branches which aren't master, and not Pull Requests, build the wheels but only upload them on tags
- ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), not(contains(variables['Build.SourceBranch'], 'master'))) }}:
  - template: publish.yml@OpenAstronomy
    parameters:
      # Only Upload to PyPI on tags
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
        pypi_connection_name : 'pypi_endpoint'
      test_extras: 'all,test'
      test_command: 'pytest --pyargs plasmapy'
      submodules: false
      targets:
        - wheels_universal
        - sdist
      dependsOn:
        - py37_linux
        - py36_windows
        - py36_minimal_conda
        - py36_conda
        - py38_linux
        - py36_astropy31
        - py37_macos
