variables:
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/plasmapy/plasmapy/_build/results?buildId=$(Build.BuildId)"
  CIBW_BUILD: cp36-* cp37-*
  CIBW_SKIP: "*-win32 *-manylinux1_i686"
  CIBW_TEST_COMMAND: pytest -p no:warnings --doctest-rst --pyargs plasmapy
  CIBW_TEST_REQUIRES: sqlalchemy scikit-image glymur beautifulsoup4 drms python-dateutil zeep tqdm asdf hypothesis pytest-astropy pytest-mock

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'
    exclude:
    - '*dev*'
    - '*pre*'
    - '*post*'
pr:
  branches:
    include:
    - '*'

jobs:
- template: azure-templates.yml
  parameters:
    name: Linux_37_offline_coverage
    os: linux
    tox: py37-offline 

- template: azure-templates.yml
  parameters:
    name: Linux_36_offline
    os: linux
    tox: py36-offline 

- template: azure-templates.yml
  parameters:
    name: Windows_37_offline
    os: windows
    tox: py37-offline  

- template: azure-templates.yml
  parameters:
    name: Windows_36_offline
    os: windows
    tox: py36-offline 

- template: azure-templates.yml
  parameters:
    name: macOS_37_offline
    os: macos
    tox: py37-offline  

- template: azure-templates.yml
  parameters:
    name: macOS_36_offline
    os: macos
    tox: py36-offline  
