
deps-run: &deps-install
  name: Install Python dependencies
  command: |
    python3 -m venv venv
    . venv/bin/activate
    pip install --user -r requirements/docs.txt
    pip install --user .

doc-run: &doc-build
  name: Build documentation
  command: make html SPHINXOPTS='-W'
  working_directory: docs

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: *deps-install
      - run: *doc-build
