blank_issues_enabled: false
contact_links:
- name: ‚ùì Usage question
  url: https://github.com/PlasmaPy/PlasmaPy/discussions
  about: |
    Ask questions and discuss with other community members here.
