name: Security ğŸ”’
description: Report a security vulnerability
labels: [security]

body:

- type: markdown
  attributes:
    value: âš ï¸ Please report critical vulnerabilities to team@plasmapy.org.

- type: textarea
  id: description
  attributes:
    label: Description
    description: What is the nature of the security vulnerability?
  validations:
    required: true

- type: dropdown
  attributes:
    label: Severity
    description: How severe is this vulnerability? (optional)
    options:
    - 'ğŸª› Low: Minor vulnerability'
    - 'âš ï¸ Medium: Limited impact'
    - 'ğŸ”¥ High: Serious risk'
    - 'ğŸ’¥ Critical: Requires immediate action (please email team@plasmapy.org)'

- type: textarea
  id: potential-impact
  attributes:
    label: Potential Impact
    description: What is the potential impact of this vulnerability? (optional)

- type: textarea
  id: mitigation
  attributes:
    label: Mitigation Strategy
    description: Do you have any suggestions for fixing this vulnerability? (optional)

- type: textarea
  id: additional-context
  attributes:
    label: Additional context
    description: Please provide any additional helpful details or related issues here. (optional)
  validations:
    required: false
