on:
  pull_request:
  push:
    branches: [master]

name: Lint
jobs:
  gitHubActionForFlake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for Flake8
      uses: StanczakDominik/GitHub-Action-for-Flake8@master
      with:
        args: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --extend-exclude ".jupyter"
