# Check that hyperlinks in the documentation are up-to-date.
#
# To check hyperlinks on a pull request, add the label entitled
# 'perform linkcheck in CI'. After installing uv, the checks can be run
# locally with
#
#    uvx nox -s linkcheck
#
# The workflow is defined in noxfile.py.


name: Check hyperlinks

on:
  schedule:
  - cron: 37 7 * * 2
  workflow_dispatch:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
    branches:
    - main

permissions: {}

jobs:

  linkcheck:
    name: Documentation linkcheck
    runs-on: ubuntu-latest
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'perform linkcheck in CI')) ||
      (github.event_name == 'schedule' && github.repository == 'PlasmaPy/PlasmaPy' && github.ref == 'refs/heads/main')

    steps:
    - name: Check out repository
      uses: actions/checkout@v5
      with:
        persist-credentials: false
    - uses: ./.github/actions/run-nox-session
      with:
        nox-session: linkcheck
        python-version: '3.14'
        github-token: ${{ secrets.GITHUB_TOKEN }}
