name: Check hyperlinks

on:
  schedule:
  - cron: 37 7 * * 2
  workflow_dispatch:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
    branches:
    - main

jobs:

  linkcheck:
    name: Documentation linkcheck
    runs-on: ubuntu-latest
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'perform linkcheck in CI')) ||
      (github.event_name == 'schedule' && github.repository == 'PlasmaPy/PlasmaPy' && github.ref == 'refs/heads/main')

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Python dependencies
      run: python -m pip install --upgrade nox uv

    - name: Install graphviz & pandoc
      run: sudo apt-get install graphviz pandoc

    - name: Check hyperlinks
      run: nox -s linkcheck
