name: add comment

on:
  pull_request_target:
    types: [opened]

jobs:
  name: Greetings
  on: [pull_request_target]

  jobs:
    greeting:
      runs-on: ubuntu-latest
      permissions:
        issues: write
        pull-requests: write
      steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: >
            Thank you for submitting your first pull request (PR) to PlasmaPy!  We invite you to check out our [**Code of Conduct**](https://docs.plasmapy.org/en/stable/CODE_OF_CONDUCT.html) and [**contributor guide**](https://docs.plasmapy.org/en/latest/contributing/index.html). ü•≥

            Please **add yourself to the list of contributors** by modifying [docs/about/credits.rst](https://github.com/PlasmaPy/PlasmaPy/blob/main/docs/about/credits.rst) in your PR to make sure that you get credit for your contribution. üîñ

            The bottom of this page includes several checks that are run for every PR. Don't worry if something broke! We break stuff all the time. üò∫ Click on "Details" next to each check to learn why a check didn't pass. Because error messages are sometimes cryptic ü§î, please feel free to ask for help. We do that all the time as well. üå∏ We can usually be reached in our [**chat room**](https://docs.plasmapy.org/en/latest/contributing/coding_guide.html) or weekly [**community meeting**](https://www.plasmapy.org/meetings/weekly) & [**office hours**]((https://www.plasmapy.org/meetings/office_hours).

            If this PR is marked as ready for review, someone should stop by soon to provide a code review and offer suggestions. ‚úÖ If you'd like more time beforehand üï∞Ô∏è, please [convert this PR into a draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft) and later on [mark it as ready for review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#marking-a-pull-request-as-ready-for-review). If you don't get a review within ‚àº2‚Äì3 weekdays, please feel free to give us a reminder.

            We thank you once again! ü™©

  checklist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Thank you for contributing! ‚ú® PlasmaPy's future depends on contributors like you, so we deeply appreciate it! üå± Please check out the [**contributor guide**](https://docs.plasmapy.org/en/latest/contributing/index.html) for more information on how to contribute.

            The following checklist will help you and the reviewer through the code review process.
             - Overall
               - [ ] Does the PR do what it intends to do?
               - [ ] Except for very minor changes, is a changelog entry included and consistent with the [changelog guide](https://docs.plasmapy.org/en/latest/contributing/changelog_guide.html)?
               - [ ] Are the continuous integration checks passing? (Most linter problems can be automagically fixed by commenting on this PR with \`pre-commit.ci autofix\`.)
             - Code
               - [ ] Is new/updated code readable and consistent with the [coding guide](https://docs.plasmapy.org/en/latest/contributing/coding_guide.html)?
               - [ ] Can any large functions be split up into shorter functions that each do one thing?
               - [ ] Are SI units used?
             - Tests
               - [ ] Are tests added/updated as required, and consistent with the [testing guide](https://docs.plasmapy.org/en/latest/contributing/testing_guide.html)?
               - [ ] Are the tests understandable?
               - [ ] Do the tests cover all important cases?
             - Docs
               - [ ] Are docs added/updated as required, and consistent with the [doc guide](https://docs.plasmapy.org/en/latest/contributing/doc_guide.html)?
               - [ ] Are the docs understandable?
               - [ ] Do the docs show up correctly in the preview, including Jupyter notebooks?`
          })
