name: Add no changelog label for autoupdates

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Label the PR
    permissions:
      contents: read
      pull-requests: write
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          // Regular expression to match the PR title pattern "Bump * from * to *"
          const bumpPattern = /^Bump .* from .* to .*/;

          // Fetch the PR
          const { data: pullRequest } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
          });

          // Check if PR title matches any of the conditions
          if (
            pullRequest.title.includes('Update pinned requirements') ||
            pullRequest.title.includes('autoupdate') ||
            bumpPattern.test(pullRequest.title)
          ) {
            // If yes, then apply the label "No changelog entry needed"
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['No changelog entry needed'],
            });
          }
