name: ğŸ· PR Size Labeler

on: pull_request

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    name: Label PR size
    steps:
    - uses: BedrockStreaming/pr-size-labeler@v1.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
