# Define continuous integration (CI) checks that are run against the
# most recent unreleased versions of upstream dependencies. The intention
# is to discover and address breaking changes before they make their way
# into a release. The checks are defined in noxfile.py.

name: upstream docs

on:
  schedule:
  - cron: 37 7 * * 1
  workflow_dispatch:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
    branches:
    - main

permissions: {}

jobs:

  weekly:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'build upstream docs')) ||
      (github.event_name == 'schedule' && github.repository == 'PlasmaPy/PlasmaPy' && github.ref == 'refs/heads/main')

    strategy:
      fail-fast: false

      matrix:
        include:

        - name: Documentation, Python 3.14, sphinx-dev, Ubuntu
          nox-session: docs_upstream(sphinx)
          python-version: '3.14'
          os: ubuntu-latest

        - name: Documentation, Python 3.14, sphinx_rtd_theme-dev, Ubuntu
          nox-session: docs_upstream(sphinx_rtd_theme)
          python-version: '3.14'
          os: ubuntu-latest

        - name: Documentation, Python 3.14, nbsphinx-dev, Ubuntu
          nox-session: docs_upstream(nbsphinx)
          python-version: '3.14'
          os: ubuntu-latest

        - name: Documentation, Python 3.14, plasmapy_sphinx-dev, Ubuntu
          nox-session: docs_upstream(plasmapy_sphinx)
          python-version: '3.14'
          os: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: ./.github/actions/run-nox-session
        with:
          nox-session: ${{ matrix.nox-session }}
          python-version: ${{ matrix.python-version }}
