# Define continuous integration (CI) checks that are run against the
# most recent unreleased versions of upstream dependencies. The intention
# is to discover and address breaking changes before they make their way
# into a release. The checks are defined in noxfile.py.

name: upstream tests

on:
  schedule:
  - cron: 37 7 * * 1
  workflow_dispatch:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
    branches:
    - main

permissions: {}

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  weekly:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'run upstream tests')) ||
      (github.event_name == 'schedule' && github.repository == 'PlasmaPy/PlasmaPy' && github.ref == 'refs/heads/main')

    strategy:
      fail-fast: false

      matrix:
        include:

        - name: Tests, Python 3.14, astropy-dev, Ubuntu
          nox-session: test_upstream(astropy)
          python-version: '3.14'
          os: ubuntu-latest

        - name: Tests, Python 3.14, numpy-dev, Ubuntu
          nox-session: test_upstream(numpy)
          python-version: '3.14'
          os: ubuntu-latest

        - name: Tests, Python 3.14, xarray-dev, Ubuntu
          nox-session: test_upstream(xarray)
          python-version: '3.14'
          os: ubuntu-latest

        - name: Tests, Python 3.14, pandas-dev, Ubuntu
          nox-session: test_upstream(pandas)
          python-version: '3.14'
          os: ubuntu-latest

        - name: Tests, Python 3.14, lmfit-dev, Ubuntu
          nox-session: test_upstream(lmfit)
          python-version: '3.14'
          os: ubuntu-latest

    steps:

      - uses: actions/checkout@v5
      with:
        persist-credentials: false

      - uses: ./.github/actions/run-nox-session
        with:
        nox-session: ${{ matrix.nox-session }}
        python-version: ${{ matrix.python-version }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
